# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chicken Coop Attendant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chicken Coop Attendant
  
  pod 'Firebase/Core'

  target 'Chicken Coop AttendantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Chicken Coop AttendantUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
